variables:
  IMAGE: ubuntu:with-hermitcore
  FINAL: rwthos/hermitcore-rs
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - prepare
  - build
  - test
  - deploy

# Stage: prepare
##############################################################################

docker:
  stage: prepare
  script:
    - docker build -t ${IMAGE} .
  tags:
    - shell
    - linux

# Stage build
##############################################################################
build:
  stage: build
  script:
    - cargo clean
    - make clean
    - make all
    - make release=1 all
  image: ${IMAGE}
  cache:
    paths:
      - target/x86_64-unknown-hermit-kernel
      - tests/target/x86_64-unknown-hermit
      - loader/target/x86_64-unknown-hermit-loader
    key: build
  artifacts:
    paths:
      - target/x86_64-unknown-hermit-kernel
      - tests/target/x86_64-unknown-hermit
      - loader/target/x86_64-unknown-hermit-loader
  tags:
    - docker

# Stage: test

##############################################################################
#test:tarpaulin:
#  stage: test
#  script:
#    - rm -rf tests loader
#    - cargo tarpaulin -v --exclude-files src/arch/aarch64
#  image: ${IMAGE}
#  tags:
#    - docker

test:cargo:
  stage: test
  script: 
    - cargo test --lib -- --test-threads=1
  image: ${IMAGE}
  tags:
    - docker

#test:uhyve:
#  stage: test
#  script:
#    - cargo install --git https://github.com/hermitcore/uhyve.git
#    - uhyve -v tests/target/x86_64-unknown-hermit/debug/rusty_tests
#    - uhyve -v tests/target/x86_64-unknown-hermit/release/rusty_tests
#  image: ${IMAGE}
#  dependencies:
#    - build
#  tags:
#    - docker

test:qemu:
  stage: test
  script:
    - make qemu
    - make release=1 qemu
  image: ${IMAGE}
  dependencies:
    - build
  tags:
    - docker

# Stage: deploy
##############################################################################

deploy:docker:
  stage: deploy
  script:
    - echo "COPY . /src" >> Dockerfile
    - echo "RUN cp /src/target/x86_64-unknown-hermit-kernel/debug/libhermit.a /root/.cargo/lib/rustlib/x86_64-unknown-hermit/lib" >> Dockerfile
    - echo "RUN rm -rf /src" >> Dockerfile
    - echo "WORKDIR /volume" >> Dockerfile
    - docker build -t ${FINAL} .
    - docker tag ${FINAL} ${FINAL}:latest
    - docker tag ${FINAL} ${FINAL}:${CI_COMMIT_TAG}
    - docker push ${FINAL}:latest
  dependencies:
    - build
  tags:
    - shell
    - linux
  only:
    - tags
