sudo: required
git:
  depth: 3
  submodules: true
services:
- docker
addons:
  apt:
    update: true
before_install:
- sudo apt-get -qq update
- sudo docker pull rwthos/hermit-cargo:latest
script:
- docker run -ti -v ${TRAVIS_BUILD_DIR}:/work:rw rwthos/hermit-cargo:latest /bin/bash -c "cd /work; ./tests.sh"
