[package]
name = "hermit"
version = "0.3.10"
authors = [
	"Stefan Lankes <slankes@eonerc.rwth-aachen.de>",
	"Colin Finck <colin.finck@rwth-aachen.de>"
]
build = "build.rs"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["unikernel", "libos"]
categories = ["os"]
description = """
RustyHermit - A Rust-based, lightweight unikernel
"""
exclude = ["/loader/*", "/tests/*", "/.travis.yml", "/.gitlab-ci.yml", ".gitignore", "/.devcontainer/*", "/.vscode/*"]

[badges]
travis-ci = { repository = "hermitcore/libhermit-rs" }

[lib]
crate-type = ["staticlib"]

[features]
vga = []
newlib = []

[dependencies]
bitflags = "1.2"
#cfg-if = "0.1"
#byteorder = { version = "1.0", default-features = false }

[dependencies.log]
version = "0.4"
default-features = false
#features = ["release_max_level_info"]

[target.'cfg(target_arch = "x86_64")'.dependencies.multiboot]
version = "0.*"

[target.'cfg(target_arch = "x86_64")'.dependencies.x86]
version = "0.*"
default-features = false

[package.metadata.cargo-xbuild]
memcpy = true

# The development profile, used for `cargo build`.
[profile.dev]
opt-level = 1      # controls the `--opt-level` the compiler builds with
debug = true       # controls whether the compiler passes `-C debuginfo`
                   # a value of `true` is equivalent to `2`
rpath = false      # controls whether the compiler passes `-C rpath`
lto = false         # controls `-C lto` for binaries and staticlibs
debug-assertions = true # controls whether debug assertions are enabled
panic = "abort" # Call abort on panic https://github.com/rust-lang/rust/pull/32900

# The release profile, used for `cargo build --release`.
[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
panic = "abort"
